SELECT CT.CITY , COUNT(C.ID) AS CUSTOMERCOUNT FROM CUSTOMERS C
INNER JOIN CITIES CT ON CT.ID =C.CITYID

-- WHERE CUSTOMERCOUNT > 10 YADA WHERE COUNT(C.ID) > 10  --> AGGREGATE FONK WHERE ÝLE KULLANILMAZ HAVÝNG ÝLE KULLAN

-- HAVING COUNT(C.ID) >10 --> GROUP BY dan sonra kullanabilirsin
GROUP BY CT.CITY

-- HAVING CUSTOMERCOUNT >10  ALÝAS TA kullanamazsýn..
HAVING COUNT(C.ID) >10  
-- ORDER BY  COUNT(C.ID) DESC
-- ORDER BY 2 DESC  -->  COLON SAYISINA GÖRE
ORDER BY CUSTOMERCOUNT DESC

-- method 2 
SELECT * FROM CITIES
SELECT *,
(SELECT COUNT(*) FROM CUSTOMERS WHERE CITYID = C.ID ) AS CUSTOMERCOUNT
FROM CITIES C
WHERE (SELECT COUNT(*) FROM CUSTOMERS WHERE CITYID = C.ID ) >10
ORDER BY  1 DESC