SELECT CT.CITY,C.GENDER,COUNT(C.ID) AS CUSTOMERCOUNT FROM CUSTOMERS C 
INNER JOIN CITIES CT ON CT.ID = C.CITYID
GROUP BY CT.CITY,C.GENDER
ORDER BY CT.CITY,C.GENDER

 
 SELECT CITY,
 (SELECT COUNT(*) FROM CUSTOMERS C WHERE CT.ID = C.CITYID) AS CUSTOMERCOUNT,
 (SELECT COUNT(*) FROM CUSTOMERS C WHERE CT.ID = C.CITYID AND GENDER ='E') AS COUNTOFMAN,
  (SELECT COUNT(*) FROM CUSTOMERS C WHERE CT.ID = C.CITYID AND GENDER ='K') AS COUNTOFWOMAN
 FROM CITIES CT

ALTER TABLE CUSTOMERS ADD AGEGROUP VARCHAR(50) 


SELECT

* , DATEDIFF(YEAR,BIRTHDATE,GETDATE()) AS AGE FROM CUSTOMERS

UPDATE CUSTOMERS SET AGEGROUP='20-35 AGE' 
WHERE DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 20 AND 35


UPDATE CUSTOMERS SET AGEGROUP='36-45 AGE' 
WHERE DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 36 AND 45

UPDATE CUSTOMERS SET AGEGROUP='46-55 AGE' 
WHERE DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 46 AND 55

UPDATE CUSTOMERS SET AGEGROUP='55-655 AGE' 
WHERE DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 55 AND 65

UPDATE CUSTOMERS SET AGEGROUP='65 AND OVER AGE' 
WHERE DATEDIFF(YEAR,BIRTHDATE,GETDATE()) > 65