SELECT 
( SELECT CITY FROM CITIES CT WHERE CT.ID = C.CITYID),

* FROM CUSTOMERS AS C

WHERE ( SELECT CITY FROM CITIES CT WHERE CT.ID = C.CITYID)='ÝSTANBUL'

-- METHOD 2



--SELECT * FROM CUSTOMERS AS C WHERE C.CITYID = 34  
-- ÜSTEKÝ KOMUT YERÝNE BUNU KULLANABÝLÝRSÝN..
SELECT * FROM CUSTOMERS AS C 
WHERE C.CITYID
IN (SELECT ID FROM CITIES WHERE CITY IN ( 'ÝSTANBUL','ANKARA'))

-- ÝLLERDE MÜÞTERÝ SAYISI
SELECT CITYID ,COUNT(CITYID) AS TOPLAM FROM CUSTOMERS WHERE CITYID =34 GROUP BY CITYID

SELECT CT.CITY,COUNT(C.ID) AS CUSTOMERSCOUNT FROM CUSTOMERS C 
INNER JOIN CITIES CT  ON CT.ID = C.CITYID WHERE CT.CITY ='ÝSTANBUL'
GROUP BY CT.CITY


SELECT *,
(SELECT COUNT(*) FROM CUSTOMERS WHERE CITYID = CT.ID) AS CUSTOMERCOUNT
FROM CITIES CT 
ORDER BY 3

